/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ZorbaJavaWrapperSWIG {
  public static void setMy_variable(double value) {
    ZorbaJavaWrapperSWIGJNI.My_variable_set(value);
  }

  public static double getMy_variable() {
    return ZorbaJavaWrapperSWIGJNI.My_variable_get();
  }

  public static int fact(int n) {
    return ZorbaJavaWrapperSWIGJNI.fact(n);
  }

  public static int my_mod(int x, int y) {
    return ZorbaJavaWrapperSWIGJNI.my_mod(x, y);
  }

  public static String get_time() {
    return ZorbaJavaWrapperSWIGJNI.get_time();
  }

}
