/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package br.com.s1mbi0se.zorbawrapper;

public class ZorbaJavaWrapperSWIGJNI {
  public final static native int create_transformation(String jarg1);
  public final static native String transform_data(int jarg1, String jarg2);
  public final static native void disconnect(int jarg1);
  public final static native void setUriPaths(String jarg1);
  public final static native void setLibPaths(String jarg1);
  public final static native void setModulePaths(String jarg1);
}
