/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package br.com.s1mbi0se.zorbawrapper;

public class ZorbaWrapper {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ZorbaWrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ZorbaWrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ZorbaJavaWrapperSWIGJNI.delete_ZorbaWrapper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ZorbaWrapper() {
    this(ZorbaJavaWrapperSWIGJNI.new_ZorbaWrapper(), true);
  }

  public int create_transformation(String transformationQuery) {
    return ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_create_transformation(swigCPtr, this, transformationQuery);
  }

  public String transform_data(int instance, String data) {
    return ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_transform_data(swigCPtr, this, instance, data);
  }

  public void disconnect(int instance) {
    ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_disconnect(swigCPtr, this, instance);
  }

  public void setUriPaths(String prop) {
    ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_setUriPaths(swigCPtr, this, prop);
  }

  public void setLibPaths(String prop) {
    ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_setLibPaths(swigCPtr, this, prop);
  }

  public void setModulePaths(String prop) {
    ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_setModulePaths(swigCPtr, this, prop);
  }

}
