/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package br.com.s1mbi0se.zorbawrapper;

public class ZorbaJavaWrapperSWIG {
  public static int create_transformation(String transformationQuery) {
    return ZorbaJavaWrapperSWIGJNI.create_transformation(transformationQuery);
  }

  public static String transform_data(int instance, String data) {
    return ZorbaJavaWrapperSWIGJNI.transform_data(instance, data);
  }

  public static void disconnect(int instance) {
    ZorbaJavaWrapperSWIGJNI.disconnect(instance);
  }

  public static void setUriPaths(String prop) {
    ZorbaJavaWrapperSWIGJNI.setUriPaths(prop);
  }

  public static void setLibPaths(String prop) {
    ZorbaJavaWrapperSWIGJNI.setLibPaths(prop);
  }

  public static void setModulePaths(String prop) {
    ZorbaJavaWrapperSWIGJNI.setModulePaths(prop);
  }

}
