/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package br.com.s1mbi0se.zorbawrapper;

public class ZorbaWrapper {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ZorbaWrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ZorbaWrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ZorbaJavaWrapperSWIGJNI.delete_ZorbaWrapper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ZorbaWrapper() {
    this(ZorbaJavaWrapperSWIGJNI.new_ZorbaWrapper(), true);
  }

  public static void disconnectAll() {
    ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_disconnectAll();
  }

  public void create_transformation(String transformationQuery) {
    ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_create_transformation(swigCPtr, this, transformationQuery);
  }

  public String transform_data(String data) {
    return ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_transform_data(swigCPtr, this, data);
  }

  public static void setUriPaths(String prop) {
    ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_setUriPaths(prop);
  }

  public static void setLibPaths(String prop) {
    ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_setLibPaths(prop);
  }

  public static void setModulePaths(String prop) {
    ZorbaJavaWrapperSWIGJNI.ZorbaWrapper_setModulePaths(prop);
  }

}
